# Generated by Django 4.1.1 on 2022-09-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_text',
            field=models.CharField(max_length=64),
        ),
    ]
