# Generated by Django 4.1.1 on 2022-09-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_options_journal_created_journal_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='created',
        ),
    ]
