# Generated by Django 4.1.1 on 2022-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
