# Generated by Django 4.1.1 on 2022-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journal_journal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
